name: Build project with PlatformIO

on:
  push:
    paths:
      - '.github/workflows/build.yaml'
      - 'src/**'
      - 'platformio.ini'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          check-latest: true
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Build project
        run: pio run
